services:
  nodejs-app:
    container_name: attention-nodejs
    image: hwengdeong/attention-app:latest
    ports:
      - "3000:3000"
    restart: always
    networks:
      - attention-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    container_name: attention-redis
    image: "redis:alpine"
    restart: always
    networks:
      - attention-network

  session-data-saver:
    container_name: attention-data-saver
    image: hwengdeong/attention-data-saver:latest
    restart: always
    env_file:
      - ./.env
    networks:
      - attention-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./dataStorage:/app/saved_data
    depends_on:
      - redis

  websocket:
    container_name: attention-websocket
    image: hwengdeong/attention-websocket:latest  
    ports:
      - "9001:9001"
    restart: always
    networks:
      - attention-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

    depends_on:
      - redis

networks:
  attention-network:
    driver: bridge
