apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  MONGO_USER: ""
  MONGO_PASSWORD: ""

apiVersion: v1
kind: ConfigMap
metadata:
  name: data-saver-configmap
data:

  REDIS_HOST: ""
  REDIS_PORT: ""
  MONGO_HOST: ""
  MONGO_PORT: ""
  MONGO_DB_NAME: ""

apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-saver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-data-saver
  template:
    metadata:
      labels:
        app: session-data-saver
    spec:
      containers:
        - name: session-data-saver-container
          image: "hwengdeong/attention-data-saver:latest"
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: mongodb-secret
            - configMapRef:
                name: data-saver-configmap